name: Triggered Workflow

on:
  repository_dispatch:
    types: [running-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: |
          echo "Running tasks in Repo B"
          sleep 180 # Sleep for 180 seconds (3 minutes)
